// === SIGNALS
  // === SIGNALS ID
    var ADDER_NOTIFY_VALIDATION_SIGNAL_ID = "-HjueoIebza7zfghr9u";

    // === STEP
      var STEP_RESET_DEPENDENCIES_SIGNAL_ID = "-Pj6hyuI4geibPUFZpof6";
      var STEP_KNOWLEDGE_IDENTIFIED_SIGNAL_ID = "-8JguepzMmgne$v5365dv";

    // === NARRATIVE BLOCK
      var NARRATIVE_BLOCK_NODE_IN_STEP_EDITOR_LEFT_CLICKED_SIGNAL_ID = "-pLkiJnBfduehU5745";

    // === RGTE
      var RGTE_MENU_BAR_RGTE_CLICKED_SIGNAL_ID = "-ItenJebg4z4g554123.vbr";
      var RGTE_MODIFICATION_ZONE_OPENED_SIGNAL_ID = "-LQjke8eknN8e7DD9t6t1";
      var RGTE_MODIFICATION_ZONE_CLOSED_SIGNAL_ID = "-ONTEO759ejdzP.berb6";

    // === RDF
      var RDF_STORE_LISTER_ELEMENT_SELECTED_ID = "-68756e4f6KEFnegzlezegL";

    // === SUBSUMPTION
      var SUBSUMPTION_CREATED_SIGNAL_ID = "-6e35ge78gr79hre6h67rqehq";
